server:
  port: 8766

spring:
  application:
    name: springcloudturbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka/
turbine:
  app-config: ClassServer,StudentServer
  aggregator:
    cluster-config: sca
  cluster-name-expression: metadata['cluster']
  instanceUrlSuffix:
    sca: StudentServer/hystrix.stream
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost